# Generated by Django 4.1.5 on 2023-01-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_alter_experience_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=80)),
                ('image', models.ImageField(help_text='Rasio harus persegi. Contoh: 600px × 600px', upload_to='certificate/')),
                ('image_label', models.CharField(max_length=50)),
                ('certificate_link', models.URLField()),
                ('certificate_label', models.CharField(max_length=50)),
                ('info_link', models.URLField()),
                ('info_label', models.CharField(max_length=50)),
            ],
        ),
    ]
