# Generated by Django 4.1.5 on 2023-01-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default='This is a description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(help_text='Rasio 1200px × 800px"', upload_to='portfolio/'),
        ),
    ]
