# Generated by Django 4.1.5 on 2023-02-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_activitylog_city_activitylog_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='city',
            field=models.CharField(default='None', editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='country',
            field=models.CharField(default='None', editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='country_code',
            field=models.CharField(default='NONE', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='isp',
            field=models.CharField(default='None', editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='isp_detail',
            field=models.CharField(default='None', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='lat',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='lon',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='region',
            field=models.CharField(default='None', editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='region_code',
            field=models.CharField(default='NONE', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timezone',
            field=models.CharField(default='None', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='webentry',
            name='city',
            field=models.CharField(default='None', editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='webentry',
            name='country',
            field=models.CharField(default='None', editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='webentry',
            name='country_code',
            field=models.CharField(default='NONE', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='webentry',
            name='isp',
            field=models.CharField(default='None', editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='webentry',
            name='isp_detail',
            field=models.CharField(default='None', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='webentry',
            name='lat',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='webentry',
            name='lon',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='webentry',
            name='region',
            field=models.CharField(default='None', editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='webentry',
            name='region_code',
            field=models.CharField(default='NONE', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='webentry',
            name='timezone',
            field=models.CharField(default='None', editable=False, max_length=20),
        ),
    ]
