# Generated by Django 4.1.5 on 2023-04-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='test', upload_to='blog/post'),
            preserve_default=False,
        ),
    ]
