# Generated by Django 4.1.5 on 2023-01-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('period', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='experience/')),
                ('label', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='skills/')),
                ('reference', models.URLField()),
                ('label', models.CharField(max_length=30)),
            ],
        ),
    ]
