# Generated by Django 4.1.5 on 2023-01-30 11:03

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('project_period', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('label', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('framework', django.contrib.postgres.fields.hstore.HStoreField(verbose_name=models.URLField())),
            ],
        ),
    ]
