# Generated by Django 4.1.5 on 2023-01-30 12:26

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_portfolio_framework_portfolio_frameworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='project_link',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='frameworks',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
