# Generated by Django 4.1.5 on 2023-02-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_webentry_city_webentry_country_webentry_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='city',
            field=models.CharField(default='None', editable=False, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='country',
            field=models.CharField(default='None', editable=False, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='country_code',
            field=models.CharField(default='None', editable=False, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='isp',
            field=models.CharField(default='None', editable=False, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='isp_detail',
            field=models.CharField(default='None', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='lat',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='lon',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='region',
            field=models.CharField(default='None', editable=False, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='region_code',
            field=models.CharField(default='None', editable=False, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='timezone',
            field=models.CharField(default='None', editable=False, max_length=20),
            preserve_default=False,
        ),
    ]
