# Generated by Django 5.2.7 on 2026-03-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='bot_type',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='webentry',
            name='bot_type',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
    ]
